apiVersion: v1
kind: ConfigMap
metadata:
 name: coredns
 namespace: kube-system
data:
 Corefile: |
   .:53 {
       errors
       ready
       health
       kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            upstream
            fallthrough in-addr.arpa ip6.arpa
       }
       prometheus :9153
       forward . /etc/resolv.conf
       cache 10
       loop
       reload
       loadbalance
   }
   # 1 = westus
   centralus.svc.cluster.local:53 {       # <---- Modify
       log
       errors
       ready
       cache 10
       forward . 104.45.233.133 {      # <---- Modify
       }
   }
   eastus.svc.cluster.local:53 {       # <---- Modify
       log
       errors
       ready
       cache 10
       forward . 137.117.11.243 {      # <---- Modify
       }
   }
